version: '3.8'

services:
  nestjs-app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mongodb://mongo:27017/nestjs
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
